Improvements to short- to midterm space heating projections
pik-piam/edgebuildings pull request #16
Opened 2024-12-13 11:54 UTC by hagento

This PR introduces an adjustment of the approach for short- to midterm space heating projections in response to Issue #6.

## Key Changes

### Current Methodology

In the existing approach, space heating demand is modeled as:

$$\frac{SH}{F \cdot P \cdot U} = \delta \cdot HDD$$

where $\delta$ is a globally determined, time-invariant parameter. While this assumption works well in higher-income regions, historical data from some regions indicate increasing $\delta$, necessitating a more dynamic and region-specific approach.

### New Approach

To better capture regional dynamics, we implemented the following changes:

1. **Region-Specific Trends for $\delta$**
  - The slope $\dot{\delta}$ is determined for each region using a linear regression of $\delta$ over time.

2. **Threshold-Based Behavior**
  - If $\dot{\delta}$ is below a threshold (currently $10^{-3}$), $\delta(t)$ is assumed constant:
    $$\delta(t) = \delta_0 = \dot{\delta}(t_0) \cdot t_0 + \text{(Intercept)}$$
    Here, $t_0$ represents the last historical year (2020).

  - If $\dot{\delta}$ exceeds the threshold, $\delta(t)$ is projected with an asymptotic function:
    $$\delta(t) = \delta_0 + \frac{\dot{\delta}_0}{c} \cdot \left[ 1 - \exp \left( - c \cdot (t - t_0) \right) \right]$$
    with:
    - $\delta_0$: Value of $\delta$ at $t_0$
    - $\dot{\delta}_0$: Slope of $\delta$ at $t_0$
    - $c = -\frac{\ln \epsilon}{\Delta t}$: Rate of adjustment, where $\epsilon$ is the fraction of slope retained, and $\Delta t = t_1 - t_0$

3. **Global Convergence**
  - Projections from the regional approach gradually converge into a global estimate by 2070, with the global $\delta$ derived from a linear regression.

4. **Deviation Adjustments**
  - Deviations ($\Delta$) between model projections and historical data are now calculated separately for regional ($\Delta_{reg}$) and global ($\Delta_{glo}$) approaches but handled consistently with previous methods.

## Additional Updates

- Added new configuration variables:
 - `deltaDecayRate` ($\epsilon$): Fraction of slope retained
 - `deltaTargetYear` ($t_1$): Year by which convergence is targeted
- Refactored variable names and code in `R/makeProjections` for better clarity and alignment with their purpose

2025-01-23 12:46 UTC, hagento commented
**NOTE**: Upon another quick review, I will have a look on some regions that do not appear to have benefitted from this adjustments (e.g. China) and will commit possible adjustments in the next week.

2025-01-28 08:56 UTC, robinhasse requested changes
Thanks @hagento, looks really good overall. I have some questions/remarks?
- I really like the renaming and better documentation in the code. While this will already help readability, I feel we should also make this function more modular and split it into more subfunctions. but that's for another day.
- I do regret a little that we introduce a special case to this otherwise pretty generic function. Conceptually, Antoine has done a pretty impressive job in creating a very versatile and flexible function here. Ideally, It like to keep the delta manipulation entirely outside of `makeProjections` and handle it separately before we run the function. But I understand that this is not really feasible. I'm sure you've though about this a lot but if you finde a way to generalise the special treatment of space heating a bit more (potentially with another argument, I'd find that super cool.
- While reviewing the code I had one thought that might not work at all, but you can tell me. Couldn't we keep the projection of space heating as it was before - no special treatment inside `makeProjections` - but then afterwards and outside of `makeProjections` compute the corrected delta as you do it here and scale the resulting projection with `deltaCorrected/deltaConstant`? That way, `makeProjections` would remain cleaner and it might even be a bit more compact and simpler to do the correction. But I'm sure I'm overlooking some of the later steps in the global convergence...
- Is there a reason, you consider 3 conditions for the special treatment? Shouldn't it be enough to just check `lhs`? Also I would always use the positive condition and run into he general procedure with an `else`.

Nice work overall!

2025-01-28 08:56 UTC, robinhasse commented on R/makeProjections.R
> +    deltaFormula <- function(prefix = "") {
again, the prefix looks like a suffix to me. But I'm also wondering if we should generalise all these functions that do similar stuff with one function that has an argument to differentiate cases for the formula...

2025-01-28 08:56 UTC, robinhasse commented on R/makeProjections.R
> +                by = "regionTarget")
```suggestion
      left_join(rename(regionalDeltas, deltaTarget = "delta"),
                by = c(regionTarget = "region"))
```

2025-01-28 08:56 UTC, robinhasse commented on R/makeProjections.R
> +  if (!(lhs == "space_heating_m2_Uval" && length(rhs) == 1 && rhs == "HDD")) {
Minor detail: I find it a bit easier to read to avoid the negation in the if condition here and swap cases. Have space heating first (with a positive condition) and then else all other cases...

2025-01-28 08:56 UTC, robinhasse commented on R/makeProjections.R
> +      reframe(delta = mean(.data[["delta"]], na.rm = TRUE)) %>%
We might want to consider weighting this average as LUX has the same weight as IND here...

2025-01-28 08:56 UTC, robinhasse commented on R/makeProjections.R
> +    rename_(.dots = setNames("projectionFinal", lhs)) %>%
```suggestion
    rename(projectionFinal = sym(lhs)) %>%
```

2025-02-03 12:51 UTC, hagento commented on R/makeProjections.R
> +                 deltaLast     = tail(predict(deltaFit), n = 1L),
Might be correct. Now the periods will be ordered beforehand - do you think this is robust enough?

2025-02-03 13:33 UTC, hagento commented on R/makeProjections.R
> +      reframe(delta = mean(.data[["delta"]], na.rm = TRUE)) %>%
This is a misconception since we group regionalDeltas beforehand. We are not interested in the averaged delta values, however, I do understand that this practice appears confusing. I have changed it with improved readability.

2025-02-04 13:44 UTC, hagento commented on R/makeProjections.R
> +    deltaFormula <- function(prefix = "") {
I reinstated the initial version since this feature is no longer needed now and provides better readability.

2025-02-04 13:53 UTC, hagento commented
@robinhasse Thanks for the thorough review of the code. I have now adapted a few things:
- Most of your suggestions were implemented. 
- The adjustment towards time-variant heating adoption has been externalised into a separate function `adjustHeatingAdoption`. This ensures that `makeProjections` remains as clean as basic as possible (Disclaimer: I only took care of the most obvious simplifications in the function, while I believe it could be even more generalized/simplified.), while the entire adjustment is being handled as a post-processing step in `buildingsProjections`. This, of course, also allows that this feature could be turned on/off but I wouldn't know why we should to that.
- Whether the adoption rate converges over time or remains at its last historic value (determined by regression) is now determined by a relative threshold, i.e. currently only regions with a positive relative slope (as a percentage change per unit increase over time) are considered for continued growth and convergence.

The plot below shows the current results. Not a lot has changed, except that we now consider more regions due to the adaptation of the threshold parameter. This might be something to further refine in the future.

![grafik](https://github.com/user-attachments/files/18658013/spaceHeating_adoptionRate_compare.pdf)

2025-02-11 09:22 UTC, robinhasse approved these changes
Cool, this is a great step foreward, @hagento - thank you! As discussed, I'd be in favor of just continuing positive trend in the adoption rate and continue falling observations constantly. Even though the curves look better in your variant, falling adoption rate doesn't seem reasonable from a socio-economic viewpoint.

2025-02-11 12:55 UTC, merged